apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        resources:
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: Aa123456aA
          - name: MYSQL_DATABASE
            value: phonebook
          - name: MYSQL_USER
            value: clarus
          - name: MYSQL_PASSWORD
            value: Pl123456
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim